name: test

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: PHPUnit Tests
        run: vendor/bin/phpunit

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "laravel-pint"
        uses: aglipanci/laravel-pint-action@2.0.0
        with:
          preset: laravel
          verboseMode: true
          testMode: true
          onlyDirty: true
